version: "3.8"

services:
  todo-flaskapp:
    image: app-image:7
    ports:
      - "3000:3000"
    container_name: flask-app
    environment:
      - FLASK_ENV=development
      - PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo


  mongo:
    image: mongodb/mongodb-community-server
    volumes:
     - flaskapp:/data/db/
    ports:
      - "27017:27017"

volumes:
  flaskapp: