networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.211.1.0/24
version: '3'
services:
  web:
    image: app-image:11
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      my_custom_network:
        ipv4_address: 172.211.1.2
    depends_on:
      - database
    environment:
      - FLASK_ENV=development
      - PORT=3000
      - MONGO_HOST=172.211.1.3
      - MONGO_PORT=27017
  database:
    image: mongodb/mongodb-community-server
    volumes:
      - flaskapp:/data/db/
    ports:
      - "27017:27017"
    networks:
      my_custom_network:
        ipv4_address: 172.211.1.3
volumes:
  flaskapp:
